from typing import Protocol


class AuthService(Protocol):
    def hash_password(self, password: str) -> str: ...

    def verify_password(self, password: str, password_hash: str) -> bool: ...

    def create_refresh_token(self) -> str: ...

    def hash_refresh_token(self, refresh_token: str) -> str: ...
